
const AUTH_KEY='aaem_auth_user', USERS_KEY='aaem_users';
const KEY={project:'aaem_project',invitation:'aaem_invitation',template:'aaem_template',guests:'aaem_guests',planner:'aaem_planner',budget:'aaem_budget',location:'aaem_location',assets:'aaem_assets',design:'aaem_design',video:'aaem_video',memories:'aaem_memories'};
function by(id){return document.getElementById(id)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function raw(k,d=null){try{let v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch{return d}}
function rawSet(k,v){localStorage.setItem(k,JSON.stringify(v))}
function user(){return raw(AUTH_KEY,null)}
function users(){return raw(USERS_KEY,[])}
function key(k){const u=user();return u?`${k}__${u.id}`:k}
function read(k,d=null){return raw(key(k),d)}
function write(k,v){rawSet(key(k),v)}
const project=()=>read(KEY.project,null), invitation=()=>read(KEY.invitation,null)
function toast(msg){let e=by('toast');if(!e){e=document.createElement('div');e.id='toast';e.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9999;background:#101828;color:white;padding:13px 17px;border-radius:13px;font-weight:750;box-shadow:0 15px 35px rgba(0,0,0,.22)';document.body.appendChild(e)}e.textContent=msg;e.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.hidden=true,2300)}
function hashPassword(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function authRequired(){if(user())return true;toast('Silakan login terlebih dahulu');setTimeout(()=>location.href='login.html?next='+encodeURIComponent(location.pathname.split('/').pop()||'dashboard.html'),350);return false}
function requireProject(){return authRequired()&&(!!project()||(toast('Buat Project terlebih dahulu'),setTimeout(()=>location.href='create.html',350),false))}
function slugify(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g,'').trim().replace(/[\s_]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'my-event'}
function signup(){const name=(by('signupName')?.value||'').trim(),email=(by('signupEmail')?.value||'').trim().toLowerCase(),pass=by('signupPassword')?.value||'',confirm=by('signupConfirm')?.value||'';if(!name||!email||pass.length<6||pass!==confirm){toast(!name?'Nama wajib diisi':!email?'Email wajib diisi':pass.length<6?'Password minimal 6 karakter':'Password tidak sama');return}let a=users();if(a.some(x=>x.email===email)){toast('Email sudah terdaftar');return}const u={id:crypto.randomUUID?.()||String(Date.now()),name,email,passwordHash:hashPassword(pass),createdAt:new Date().toISOString()};a.push(u);rawSet(USERS_KEY,a);rawSet(AUTH_KEY,{id:u.id,name,email});location.href=new URLSearchParams(location.search).get('next')||'dashboard.html'}
function login(){const email=(by('loginEmail')?.value||'').trim().toLowerCase(),pass=by('loginPassword')?.value||'',u=users().find(x=>x.email===email&&x.passwordHash===hashPassword(pass));if(!u){toast('Email atau password salah');return}rawSet(AUTH_KEY,{id:u.id,name:u.name,email:u.email});location.href=new URLSearchParams(location.search).get('next')||'dashboard.html'}
function logout(){localStorage.removeItem(AUTH_KEY);location.href='index.html'}
function gateProtected(){const protectedPages=['dashboard.html','invitation-maker.html','invitation-editor.html','invitation-detail.html','photo-maker.html','video-maker.html','design-maker.html','ai-creator.html','guest-manager.html','location.html','event-planner.html','budget.html','analytics.html','memories.html'];const p=location.pathname.split('/').pop()||'index.html';if(protectedPages.includes(p)&&!user()){location.href='login.html?next='+encodeURIComponent(p)}}

function createProject(){if(!authRequired())return;const name=(by('eventName')?.value||'').trim(),type=by('eventType')?.value||'Wedding',date=by('eventDate')?.value||'',time=by('eventTime')?.value||'',venue=(by('eventLocation')?.value||'').trim();if(!name){toast('Masukkan nama event');return}const p={id:crypto.randomUUID?.()||String(Date.now()),name,type,date,time,location:venue,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};write(KEY.project,p);write(KEY.invitation,{title:'Your Event',opening:'Together with our families, we invite you to celebrate this special moment.',date,time:time||'10:00',venue:venue||'Your Venue',slug:slugify(name),template:'International Classic',published:false,views:0});location.href='dashboard.html'}
function chooseTemplate(name){if(!requireProject())return;const inv=invitation()||{};write(KEY.template,name);write(KEY.invitation,{...inv,template:name});location.href='invitation-editor.html'}
function saveInvitation(){if(!requireProject())return;const old=invitation()||{},d={...old,title:(by('title')?.value||'Your Event').trim(),opening:(by('opening')?.value||'').trim(),date:by('date')?.value||'',time:by('time')?.value||'10:00',venue:(by('venue')?.value||'Your Venue').trim(),slug:slugify(by('slug')?.value||''),template:by('template')?.value||'International Classic'};write(KEY.invitation,d);toast('Invitation tersimpan');setTimeout(()=>location.href='invitation-detail.html',250)}
function publishInvitation(){if(!requireProject())return;const inv=invitation();write(KEY.invitation,{...inv,published:true});toast('Invitation published');setTimeout(()=>location.href='invitation-detail.html',250)}
function shareInvitation(){if(!authRequired())return;const inv=invitation();if(!inv){toast('Buat invitation terlebih dahulu');return}const payload={title:inv.title||'Your Event',opening:inv.opening||'',date:inv.date||'',time:inv.time||'',venue:inv.venue||'',template:inv.template||'International Classic',slug:inv.slug||'my-event'};const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(payload))));const url=new URL('public-invitation.html',location.href);url.searchParams.set('data',encoded);if(navigator.share)navigator.share({title:payload.title,text:'You are invited',url:url.href}).catch(()=>{});else navigator.clipboard?.writeText(url.href).then(()=>toast('Link invitation disalin')).catch(()=>prompt('Copy invitation link',url.href))}
function openSharedInvitation(){try{const d=new URLSearchParams(location.search).get('data');return d?JSON.parse(decodeURIComponent(escape(atob(d)))):null}catch{return null}}
function recordPublicView(){if(!user())return;const i=invitation();if(i){i.views=Number(i.views||0)+1;write(KEY.invitation,i)}}

function addGuest(){if(!requireProject())return;const name=(by('guestName')?.value||'').trim();if(!name){toast('Nama guest wajib diisi');return}const a=read(KEY.guests,[]);a.push({id:Date.now(),name,phone:by('guestPhone')?.value||'',email:by('guestEmail')?.value||'',group:by('guestGroup')?.value||'General',rsvp:'Pending',sent:false,checkedIn:false,token:slugify(name)+'-'+Date.now()});write(KEY.guests,a);['guestName','guestPhone','guestEmail'].forEach(id=>{if(by(id))by(id).value=''});renderGuests();toast('Guest ditambahkan')}
function guestLink(g){const inv=invitation()||{},base=new URL('public-invitation.html',location.href),payload={...inv,title:inv.title||'Your Event',guest:g.name};base.searchParams.set('data',btoa(unescape(encodeURIComponent(JSON.stringify(payload)))));return base.href}
function renderGuests(){const e=by('guestList');if(!e)return;const a=read(KEY.guests,[]);if(by('guestTotal'))by('guestTotal').textContent=a.length+' guests';e.innerHTML=a.length?a.map(g=>`<div class="list-row"><span><b>${esc(g.name)}</b><small>${esc(g.group)} · ${esc(g.phone||'No phone')} · ${esc(g.email||'No email')}</small></span><div class="actions"><button class="btn light" onclick="copyGuestLink('${g.token}')">Link</button><button class="btn light" onclick="toggleCheckIn(${g.id})">${g.checkedIn?'Checked in':'Check-in'}</button><strong>${esc(g.rsvp)}</strong></div></div>`).join(''):'<div class="empty">Belum ada guest.</div>'}
function copyGuestLink(token){const g=read(KEY.guests,[]).find(x=>String(x.token)===String(token));if(!g)return;navigator.clipboard?.writeText(guestLink(g)).then(()=>toast('Personal guest link disalin')).catch(()=>prompt('Copy guest link',guestLink(g)))}
function toggleCheckIn(id){const a=read(KEY.guests,[]),g=a.find(x=>x.id===id);if(g){g.checkedIn=!g.checkedIn;write(KEY.guests,a);renderGuests();toast(g.checkedIn?'Guest checked in':'Check-in dibatalkan')}}
function submitRsvp(){const name=(by('guest')?.value||'').trim();if(!name){toast('Masukkan nama');return}const ans=by('answer')?.value||'',status=ans.startsWith('Yes')?'Confirmed':ans.startsWith('Sorry')?'Declined':'Maybe';const a=read(KEY.guests,[]),g=a.find(x=>x.name.toLowerCase()===name.toLowerCase());if(g){g.rsvp=status;g.pax=by('pax')?.value||'1 guest'}else a.push({id:Date.now(),name,phone:'',email:'',group:'Guest',rsvp:status,pax:by('pax')?.value||'1 guest',checkedIn:false});write(KEY.guests,a);if(by('r')){by('r').textContent='✓ RSVP berhasil dicatat.';by('r').className='notice'}}
function addTask(){if(!requireProject())return;const task=(by('taskName')?.value||'').trim();if(!task){toast('Task wajib diisi');return}const a=read(KEY.planner,[]);a.push({id:Date.now(),task,date:by('taskDate')?.value||'',owner:by('taskOwner')?.value||'',status:'To do'});write(KEY.planner,a);renderTasks();toast('Task ditambahkan')}
function renderTasks(){const e=by('taskList');if(!e)return;const a=read(KEY.planner,[]);e.innerHTML=a.length?a.map(x=>`<div class="list-row"><span><b>${esc(x.task)}</b><small>${esc(x.date||'No deadline')} · ${esc(x.owner||'Unassigned')}</small></span><button class="btn light" onclick="toggleTask(${x.id})">${esc(x.status)}</button></div>`).join(''):'<div class="empty">Belum ada task.</div>'}
function toggleTask(id){const a=read(KEY.planner,[]),x=a.find(v=>v.id===id);if(x){x.status=x.status==='Done'?'To do':'Done';write(KEY.planner,a);renderTasks()}}
function addBudget(){if(!requireProject())return;const category=by('budgetCat')?.value||'Other',planned=Number(by('budgetPlan')?.value||0),actual=Number(by('budgetActual')?.value||0);const a=read(KEY.budget,[]);a.push({id:Date.now(),category,planned,actual});write(KEY.budget,a);renderBudget();updateBudgetSummary();toast('Budget ditambahkan')}
function renderBudget(){const e=by('budgetList');if(!e)return;const a=read(KEY.budget,[]);e.innerHTML=a.length?a.map(x=>`<div class="list-row"><span><b>${esc(x.category)}</b><small>Planned Rp ${x.planned.toLocaleString('id-ID')}</small></span><strong>Actual Rp ${x.actual.toLocaleString('id-ID')}</strong></div>`).join(''):'<div class="empty">Belum ada budget.</div>'}
function updateBudgetSummary(){const a=read(KEY.budget,[]),p=a.reduce((s,x)=>s+Number(x.planned||0),0),r=a.reduce((s,x)=>s+Number(x.actual||0),0);if(by('totalPlan'))by('totalPlan').textContent='Rp '+p.toLocaleString('id-ID');if(by('totalActual'))by('totalActual').textContent='Rp '+r.toLocaleString('id-ID');if(by('remaining'))by('remaining').textContent='Rp '+(p-r).toLocaleString('id-ID')}
function saveLocation(){if(!requireProject())return;const x={name:(by('locName')?.value||'').trim(),address:(by('locAddress')?.value||'').trim(),url:(by('locUrl')?.value||'').trim(),type:by('locType')?.value||'Main Venue'};write(KEY.location,x);if(by('locSaved'))by('locSaved').textContent='✓ Location tersimpan';renderLocation()}
function renderLocation(){const e=by('locationPreview');if(!e)return;const x=read(KEY.location,null);e.innerHTML=x?`<div class="notice">📍 ${esc(x.name||'Venue')} · ${esc(x.address||'')}</div>${x.url?`<a class="btn dark" href="${esc(x.url)}" target="_blank" rel="noopener">Open Map / Directions →</a>`:''}`:'<div class="empty">Belum ada location.</div>'}
function generateConcept(){if(!requireProject())return;const p=(by('aiPrompt')?.value||'').trim();if(!p){toast('Masukkan prompt');return}const result={prompt:p,theme:'Elegant celebration',palette:'Plum · Rose · Ivory',typography:'Editorial Serif + Clean Sans',storyboard:'Opening → Main moment → Details → RSVP → Closing'};write('aaem_ai',result);if(by('aiResult'))by('aiResult').innerHTML=`<span class="eyebrow">AI DRAFT</span><h2>${esc(result.theme)}</h2><p>${esc(result.prompt)}</p><div class="list"><div class="list-row"><span>Palette</span><strong>${result.palette}</strong></div><div class="list-row"><span>Typography</span><strong>${result.typography}</strong></div><div class="list-row"><span>Storyboard</span><strong>${result.storyboard}</strong></div></div><div class="actions"><a class="btn primary" href="invitation-editor.html">Use for Invitation →</a></div>`}
function saveStudio(kind){if(!requireProject())return;const k=kind==='photo'?KEY.assets:kind==='video'?KEY.video:KEY.design;write(k,{updatedAt:new Date().toISOString(),notes:(by(kind+'Notes')?.value||'').trim(),assetName:by(kind+'Upload')?.files?.[0]?.name||''});toast('Workspace tersimpan')}
function fillEditor(){if(!by('title'))return;const i=invitation()||{},p=project()||{};by('title').value=i.title||p.name||'Your Event';by('opening').value=i.opening||'';by('date').value=i.date||p.date||'';by('time').value=i.time||p.time||'10:00';by('venue').value=i.venue||p.location||'Your Venue';by('slug').value=i.slug||slugify(p.name);if(by('template'))by('template').value=i.template||'International Classic';const img=by('templateVisual');if(img){img.src='assets/'+slugify(i.template||'International Classic')+'.svg';img.onerror=()=>img.style.display='none'}updateEditorPreview()}
function updateEditorPreview(){if(!by('pvTitle'))return;by('pvTitle').textContent=by('title')?.value||'Your Event';by('pvOpening').textContent=by('opening')?.value||'';by('pvDate').textContent=(by('date')?.value||'Your date')+' · '+(by('time')?.value||'10:00');by('pvVenue').textContent=by('venue')?.value||'Your Venue'}
function renderDetail(){const i=invitation()||{},p=project()||{};['title','opening','venue'].forEach(id=>{if(by(id))by(id).textContent=i[id]||p.name||'Your Event'});if(by('date'))by('date').textContent=(i.date||p.date||'Your date')+' · '+(i.time||p.time||'10:00');if(by('d1'))by('d1').textContent=i.date||p.date||'Your date';if(by('d2'))by('d2').textContent=i.time||p.time||'10:00';if(by('venue'))by('venue').textContent=i.venue||p.location||'Your Venue';const loc=read(KEY.location,null);if(by('direction')&&loc?.url){by('direction').href=loc.url;by('direction').style.display='inline-flex'}if(by('publishedStatus'))by('publishedStatus').textContent=i.published?'Published':'Draft';countdown(i.date,i.time)}
function countdown(ds,ts){const els=['cdDays','cdHours','cdMinutes','cdSeconds'].map(by);if(els.every(x=>!x))return;const tick=()=>{if(!ds){els.forEach(x=>x&&(x.textContent='—'));return}const target=new Date(ds+'T'+(ts||'00:00')),d=Math.max(0,target-Date.now());const sec=Math.floor(d/1000);[Math.floor(sec/86400),Math.floor(sec%86400/3600),Math.floor(sec%3600/60),sec%60].forEach((v,i)=>els[i]&&(els[i].textContent=v));};tick();setInterval(tick,1000)}
function renderAnalytics(){const a=read(KEY.guests,[]),i=invitation()||{},c=a.filter(x=>x.rsvp==='Confirmed').length,d=a.filter(x=>x.rsvp==='Declined').length,p=a.length-c-d;for(const [id,v] of [['aViews',i.views||0],['aConfirmed',c],['aDeclined',d],['aPending',p]])if(by(id))by(id).textContent=v;if(by('checkins'))by('checkins').textContent=a.filter(x=>x.checkedIn).length;const rate=a.length?Math.round(c/a.length*100):0;if(by('rate'))by('rate').textContent=rate+'%';if(by('bar'))by('bar').style.width=rate+'%'}
document.addEventListener('DOMContentLoaded',()=>{
 gateProtected();
 if(by('authUserName')){by('authUserName').textContent=user()?.name||'Guest';if(by('accountEmail'))by('accountEmail').textContent=user()?.email||'';}
renderGuests();renderTasks();renderBudget();updateBudgetSummary();renderLocation();fillEditor();renderDetail();renderAnalytics();
 if(by('guestTotal'))by('guestTotal').textContent=read(KEY.guests,[]).length+' guests';
 if(by('budgetItems'))by('budgetItems').textContent=read(KEY.budget,[]).length;
 if(by('checkins'))by('checkins').textContent=read(KEY.guests,[]).filter(x=>x.checkedIn).length;
document.querySelectorAll('#title,#opening,#date,#time,#venue').forEach(e=>e.addEventListener('input',updateEditorPreview));});
