function getProject(){return JSON.parse(localStorage.getItem('aaem_project')||'null')}
function getInvitation(){return JSON.parse(localStorage.getItem('aaem_invitation')||'null')}
function setText(id,value){const e=document.getElementById(id);if(e)e.textContent=value}
function toast(msg){let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.style.cssText='position:fixed;right:18px;bottom:18px;z-index:99;background:#111827;color:#fff;padding:12px 16px;border-radius:12px;box-shadow:0 12px 30px rgba(0,0,0,.2)';document.body.appendChild(e)}e.textContent=msg;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2500)}
function saveProject(p){localStorage.setItem('aaem_project',JSON.stringify(p))}
function createProject(){const name=(document.getElementById('eventName')?.value||'').trim();const type=document.getElementById('eventType')?.value||'Custom Event';const date=document.getElementById('eventDate')?.value||'';if(!name){toast('Masukkan nama event terlebih dahulu');return}saveProject({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,type,date,createdAt:new Date().toISOString()});location.href='dashboard.html'}
function chooseTemplate(name){localStorage.setItem('aaem_template',name);location.href='invitation-editor.html'}
function copyLink(){navigator.clipboard?.writeText(location.href).then(()=>toast('Link berhasil disalin')).catch(()=>toast('Salin URL dari address bar'))}

function listStore(key){return JSON.parse(localStorage.getItem(key)||'[]')}
function saveList(key,v){localStorage.setItem(key,JSON.stringify(v))}
function addGuest(){const n=document.getElementById('guestName')?.value.trim();if(!n)return toast('Masukkan nama tamu');const a=listStore('aaEventMakerGuests');a.push({name:n,phone:document.getElementById('guestPhone')?.value||'',group:document.getElementById('guestGroup')?.value||'Other',rsvp:'Pending'});saveList('aaEventMakerGuests',a);renderGuests();toast('Guest added')}
function renderGuests(){const e=document.getElementById('guestList');if(!e)return;e.innerHTML=listStore('aaEventMakerGuests').map((g,i)=>`<div class="list-row"><span>${g.name} · ${g.group}</span><strong>${g.rsvp}</strong></div>`).join('')||'<div class="list-row">No guests yet.</div>'}
function addTask(){const n=document.getElementById('taskName')?.value.trim();if(!n)return toast('Masukkan task');const a=listStore('aaEventMakerPlanner');a.push({task:n,date:document.getElementById('taskDate')?.value||'',owner:document.getElementById('taskOwner')?.value||'',status:'To do'});saveList('aaEventMakerPlanner',a);renderTasks();toast('Task added')}
function renderTasks(){const e=document.getElementById('taskList');if(!e)return;e.innerHTML=listStore('aaEventMakerPlanner').map(t=>`<div class="list-row"><span>${t.task}<small>${t.date||''} ${t.owner||''}</small></span><strong>${t.status}</strong></div>`).join('')||'<div class="list-row">No tasks yet.</div>'}
function addBudget(){const plan=Number(document.getElementById('budgetPlan')?.value||0),actual=Number(document.getElementById('budgetActual')?.value||0);const a=listStore('aaEventMakerBudget');a.push({category:document.getElementById('budgetCat')?.value||'Other',planned:plan,actual});saveList('aaEventMakerBudget',a);renderBudget();toast('Budget added')}
function renderBudget(){const e=document.getElementById('budgetList');if(!e)return;const a=listStore('aaEventMakerBudget');e.innerHTML=a.map(x=>`<div class="list-row"><span>${x.category}</span><strong>Planned ${x.planned.toLocaleString()} · Actual ${x.actual.toLocaleString()}</strong></div>`).join('')||'<div class="list-row">No budget items yet.</div>'}
function generateConcept(){const p=document.getElementById('aiPrompt')?.value.trim();if(!p)return toast('Masukkan prompt');const e=document.getElementById('aiResult');if(e)e.innerHTML=`<h2>Concept draft</h2><p><strong>Prompt:</strong> ${p}</p><p>Theme, color palette, typography, invitation copy and visual direction can be developed from this brief.</p>`}
document.addEventListener('DOMContentLoaded',()=>{renderGuests();renderTasks();renderBudget()})
